### PR TITLE
Git Ignore .idea settings files

### LINKED ISSUE #49: Adding idea to Git Ignore
- adding .idea folder into the .gitignore file

### PR DESCRIPTION
**Pull request by MortarDefender**
- adding .idea folder into .gitignore

fix: #49

### CODE REVIEW

**Review by kobihk — CHANGES_REQUESTED** [review]
@MortarDefender the title is too generic maybe you can change it to something like:
Git Ignore .idea settings files

**Comment by MortarDefender** [comment]
Done

**Comment by kobihk** [comment]
@MortarDefender please ask CR from your team members

**Review by RonHachmon — APPROVED** [review]
Approved

**Review by danninon — APPROVED** [review]
this is appropriate

**Review by kobihk — APPROVED** [review]

**Pull request merged**
