### PR TITLE
Documentation

### LINKED ISSUE #12: Adding documentation Files
Files:
1. README.md - project introduction
2. CONTRIBUTING.md - The contribution guide

### PR DESCRIPTION
**Pull request by danninon**
1. Added README.md
2. main directory contains static pictures for README.md
3. Added CONTRIBUTING.md

fix: #12

### CODE REVIEW

**Review by YaelD — APPROVED** [review]
looks good to me

**Review by RonHachmon — APPROVED** [review]
Looks good to me

**Review by MortarDefender — APPROVED** [review]
Looks good

**Review by nemerna — APPROVED** [review]
i would add 2 notes , while approving.

1) i suggest using a directory that is dedicated for pictures only.
2) you was supposed to include the "[readme.md](https://github.com/redhat-beyond/lets-meet/pull/13/commits/34542fd9c2c0f990c15119418808ebbd19f07ebd#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)" file in a separate commit.

**Pull request merged**
