### PR TITLE
PyTest Environment

### LINKED ISSUE #22: PyTest Addition
- adding pytest to the pipfile, pipfile.lock
- adding pytest to run automatically for each pr created
- adding pillow library for user pictures addition

### PR DESCRIPTION
**Pull request by MortarDefender**
- adding the pytest library to the pipfile for tests
- adding pillow library to the pipfile for ImageField in users
- adding pytest to the github workflows
- adding a pytest.ini for config

fix: #22

### CODE REVIEW

**Review by YaelD — APPROVED** [review]
looks good to me

**Review by BelikovYoav — APPROVED** [review]
looks good

**Review by kobihk — CHANGES_REQUESTED** [review]
@MortarDefender Please fix the typo in the PR title "PyTest Envairment"

**Comment by MortarDefender** [comment]
done

**Review by kobihk — APPROVED** [review]

**Pull request merged**
