### PR TITLE
Role 3: setting up Django web framework

### LINKED ISSUE #4: Role 3 : setting up Django website
setting up the Pipnev
providing local http acccess to the vm
bootstraping a basic django website

### PR DESCRIPTION
**Pull request by RavidYael**
setting up Django framework to our website:

1. setting up the Pipnev
2. providing local http acccess to the vm
3. bootstraping a basic django website

fix : #4

### CODE REVIEW

**Review by danninon — APPROVED** [review]
Looking good!

**Review by MortarDefender — APPROVED** [review]
changes are approved

**Review by YaelD — APPROVED** [review]
changes are approved

**Comment by kobihk** [comment]
@RavidYael please create a new issue and add the link of it to this PR description
for more details, you can ask @RonHachmon

**Comment by kobihk** [comment]
@RavidYael "issue" is like a "bug" 
so IMHO better to write it in the PR description like:
fix: #4 
instead of:
link to the issue of this PR: #4

**Review by kobihk — APPROVED** [review]

**Pull request merged**
