### PR TITLE
Adding a Vagrantfile for spinning up a development VM

### LINKED ISSUE #2: adding vagrant file
Vagrantfile PR: https://github.com/redhat-beyond/Beyond-07-team-3/pull/1

### PR DESCRIPTION
**Pull request by RonHachmon**
setting memory on vm machine to 1024,
And enabling file sharing between VM to repository
fixes : #2

### CODE REVIEW

**Review by kobihk — CHANGES_REQUESTED** [review]
Please create an issue for this PR then please add a link of it to the PR description

**Comment by RonHachmon** [comment]
done #2

**Review by kobihk — APPROVED** [review]

**Comment by MortarDefender** [comment]
changes are approved

**Comment by kobihk** [comment]
@MortarDefender 
To be able to add "Approve" to PR you need to:

- Go to "Files changed" tab( https://github.com/redhat-beyond/Beyond-07-team-3/pull/1/files )
- Click on "Review changes"(in the right side)
- Choose the "Approve" radio button(unless you have comments or request for changes)

**Review by MortarDefender — APPROVED** [review]
changes are approved

**Review by danninon — APPROVED** [review]

**Pull request merged**
