### PR TITLE
Typos

### LINKED ISSUE #16: Fix typos in all English file
There are some typos in README.md. 
I suggest you check all files for English typos.

### PR DESCRIPTION
**Pull request by MortarDefender**
- fix typos in CONTRIBUTING.md and README.md
    - fix typos in index.html
   
fix: #16

### CODE REVIEW

**Comment by MortarDefender** [comment]
@YaelD @RavidYael  @danninon  @BelikovYoav  @RonHachmon 
can you please write a code review on this pull request, 
see what has changed, and if there is a need to add or modify anything.
Thanks

**Review by RonHachmon — APPROVED** [review]
seems great, approved

**Review by danninon — APPROVED** [review]
Nice touches.

**Review by brochwerger — APPROVED** [review]
As far a I can see, all typos were corrected. Great job

**Pull request merged**
